@startuml us2211_domain_model
title US2211 - Domain Model
hide circle
skinparam backgroundColor #F0F0F0

rectangle "Staff" #Lavender {

	class "**Staff**" as staff <<AggregateRoot>><<Entity>>
	{
	}

	class "Staff\n**Mechanographic**\n**Number**" as staff_id <<ID>><<Value>>
	{
		+ id
	}

	class "Staff\n**Name**" as staff_name <<Value>>
	{
		+ name
	}

	class "Staff\n**Email**" as staff_email <<Value>>
	{
		+ email
	}

	class "Staff\n**Phone Number**" as staff_phone_number <<Value>>
	{
		+ phoneNumber
	}

	class "Staff\n**Status**" as staff_status <<Enum>>
	{
		+ ACTIVE
		+ INACTIVE
		+ TEMPORARILY_REASSIGNED
	}

	class "Staff\n**Operational**\n**Window**" as staff_op_window
	{
		+ startWeekDay
		+ endWeekDay
		+ dayStartTime
		+ dayEndTime
	}

	staff "1" --> staff_op_window
	staff --> "1" staff_id
	staff --> "1" staff_name
	staff --> "1" staff_email
	staff --> "1" staff_phone_number
	staff --> "1" staff_status
}

rectangle "System"{
	class "**User**" as user <<AggregateRoot>><<Entity>>
	{
		...
	}
}

rectangle "Qualifications" {
	class "**Qualification**" as quali <<AggregateRoot>><<Entity>>
	{
		...
	}
}

rectangle "Vessel Visit Notifications" {

	class "**Vessel Visit**\n**Notification**" as vessel_visit_notif <<AggregateRoot>><<Entity>>
	{
		...
	}



	class "Vessel Visit\nNotification\n**Vessel Berth**" as vessel_berth <<Entity>>
	{
		...
	}

	


	class "Vessel Visit\nNotification\n**Operational Task**" as op_task <<Entity>>
	{
		...
	}

}


user "1" --> "*" staff : "(Logistics Operator)\nregisters/manages"

op_task "1" -> "*" staff : "mobilizes"

staff "*" --> "*" quali : "has"

vessel_berth "1" -u-> "*" op_task : "encapsulates"
vessel_visit_notif <-d- vessel_berth : "responds to"





@enduml