@startuml mapping_view_n4
skinparam Linetype polyline

title Level 4 - Implementation Logic Mapping View

package "PortTiT" {

    package "Routes" as rt {

    }

    package "Application" {
        package "Controllers" as controller {

        }

        package "Services" as service{

        }
    }

    package "Infrastructure"{

        package "Persistency" {

            package "Repositories" as repo {

            }

            package "Context" as ctx {

            }
        }

        package "Utilities" {

            package "Page<T>" as page {

            }
        }
    }

    package "Domain"{
        package "Entities" as ent {

        }

        package "ValueObjects" as vo {

        }
    }
}

controller ..> service
service ..> repo
service ..> ent

ent ..> vo

repo ..> ctx
rt ..> controller

circle "API" as api #LightBlue

api --o masterdata

rectangle "Master Data" as masterdata <<Container C4>> {
	
	[row 1 empty] as empty1 #red
	[BackEnd Controllers] as controller2

	[BackEnd Services] as service2
	[row 2 empty] as empty2 #red

	[BackEnd Repositories] as repository
	[row 3 empty] as empty3 #red

	[DTO] as dtos
	[BackEnd Domain] as domain
	database "Backend\nDatabase" as database

	hide empty1
	hide empty2
	hide empty3
} 

' row one 
controller2 -d(0- dtos : "DTO\nAPI"
controller2 -(0- service2 : "SERVICE\nAPI"
empty1 -l- controller2
empty1 -d- dtos

' row three
service2 -u(0- dtos : "DTO\nAPI"
empty2 -l- service2
empty2 -u- dtos

'row four
service2 -d(0- repository : "SERVICE\nAPI"
service2 -(0- domain : "DOMAIN\nAPI"
repository -u(0- domain : "DOMAIN\nAPI"
empty3 -l- repository
empty2 -d- domain
empty3 -u- domain

repository -d(0- database : "DATABASE\nAPI"

controller2 ..> controller : "manifests"
service2 ..> service : "manifests"
repository ..> repo : "manifests"
domain ..> ent : "manifests"

@enduml