@startuml logicview_n4
skinparam Linetype polyline

circle "EFCore" as efcore #LightBlue
circle "API" as api #LightBlue


rectangle "EFCore" as efcore <<Container C4>> {
	
	component "Entity Framework" as dbcontext
	database "Database" as database

	dbcontext -- database
} 

api -l-o dbcontext

@enduml