@startuml logicview_n4
skinparam Linetype polyline

circle "API" as api #LightBlue

api --o masterdata

rectangle "Master Data" as masterdata <<Container C4>> {
	
	[row 1 empty] as empty1 #red
	[BackEnd Controllers] as controller

	[BackEnd Services] as service
	[row 2 empty] as empty2 #red

	[BackEnd Repositories] as repository
	[row 3 empty] as empty3 #red

	[DTO] as dtos
	[BackEnd Domain] as domain
	database "Backend\nDatabase" as database

	hide empty1
	hide empty2
	hide empty3
} 

' row one 
controller -d(0- dtos : "DTO\nAPI"
controller -(0- service : "SERVICE\nAPI"
empty1 -l- controller
empty1 -d- dtos

' row three
service -u(0- dtos : "DTO\nAPI"
empty2 -l- service
empty2 -u- dtos

'row four
service -d(0- repository : "SERVICE\nAPI"
service -(0- domain : "DOMAIN\nAPI"
repository -u(0- domain : "DOMAIN\nAPI"
empty3 -l- repository
empty2 -d- domain
empty3 -u- domain

repository -d(0- database


@enduml