@startuml logicview_n3
skinparam Linetype polyline


circle "API" as api #LightBlue

api --o masterdata

rectangle "Master Data" as masterdata {
	
	[Backend] as backend

	database "Backend\nDatabase" as database

} 

backend -(0- database : "Database\nApi"

@enduml