@startuml logicview_n4
skinparam Linetype polyline


circle "API" as api #LightBlue

api --o masterdata

rectangle "Master Data" as masterdata {
	
	[Backend] as backend
	[EFCore] as efcore

	database "Backend\nDatabase" as database

} 

backend -(0- efcore : "EFCore\nApi"
efcore -r(0- database : "DB\nAPI"

@enduml