import { test, expect } from '@playwright/test';

test('Ensure dock is created with valid data and is listed', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('link', { name: 'Docks' }).click();
  await page.getByRole('link', { name: 'add Create Dock' }).click();
  await page.getByPlaceholder('Dock code').click();
  await page.getByPlaceholder('Dock code').fill('DCKTEST01');
  await page.getByPlaceholder('Dock name').click();
  await page.getByPlaceholder('Dock name').fill('Test Dock');
  await page.getByPlaceholder('Dock location').click();
  await page.getByPlaceholder('Dock location').fill('North Terminal');
  await page.getByPlaceholder('Length in meters').click();
  await page.getByPlaceholder('Length in meters').fill('500');
  await page.getByPlaceholder('Depth in meters').click();
  await page.getByPlaceholder('Depth in meters').fill('25');
  await page.getByPlaceholder('Draft in meters').click();
  await page.getByPlaceholder('Draft in meters').fill('22');
  await page.getByPlaceholder('Select supported vessel types').click();
  await page.locator('.option').first().click();
  await page.getByRole('button', { name: 'Create', exact: true }).click();
  await page.getByRole('link', { name: 'search View Docks' }).click();
  await page.getByRole('main').filter({ hasText: 'Dock Dashboard Search Docks' }).getByPlaceholder('Search...').click();
  await page.getByRole('main').filter({ hasText: 'Dock Dashboard Search Docks' }).getByPlaceholder('Search...').fill('DCKTEST01');
  await expect(page.getByRole('link', { name: 'Test Dock' }).first()).toBeVisible();
});

test('Ensure dock is updated correctly on update', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('link', { name: 'Docks' }).click();
  await page.getByRole('link', { name: 'add Create Dock' }).click();
  await page.getByPlaceholder('Dock code').click();
  await page.getByPlaceholder('Dock code').fill('DCKEDIT01');
  await page.getByPlaceholder('Dock name').click();
  await page.getByPlaceholder('Dock name').fill('Dock to Edit');
  await page.getByPlaceholder('Dock location').click();
  await page.getByPlaceholder('Dock location').fill('East Terminal');
  await page.getByPlaceholder('Length in meters').click();
  await page.getByPlaceholder('Length in meters').fill('550');
  await page.getByPlaceholder('Depth in meters').click();
  await page.getByPlaceholder('Depth in meters').fill('53');
  await page.getByPlaceholder('Draft in meters').click();
  await page.getByPlaceholder('Draft in meters').fill('50');
  await page.getByPlaceholder('Select supported vessel types').click();
  await page.locator('.option').first().click();
  await page.getByRole('button', { name: 'Create', exact: true }).click();
  await page.getByRole('link', { name: 'search View Docks' }).click();
  await page.getByRole('main').filter({ hasText: 'Dock Dashboard Search Docks' }).getByPlaceholder('Search...').click();
  await page.getByRole('main').filter({ hasText: 'Dock Dashboard Search Docks' }).getByPlaceholder('Search...').fill('DCKEDIT01');
  await page.getByRole('link', { name: 'Dock to Edit' }).first().click();
  await page.getByRole('button', { name: 'Edit Dock' }).click();
  await page.getByPlaceholder('Dock name').click();
  await page.getByPlaceholder('Dock name').fill('Dock to Edit EDITED');
  await page.getByRole('button', { name: 'Save' }).click();
  await expect(page.getByRole('heading')).toContainText('Dock to Edit EDITED');
});

test('Ensure validation prevents creating dock with empty fields or incorrect data', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('link', { name: 'Docks' }).click();
  await page.getByRole('link', { name: 'add Create Dock' }).click();
  await page.getByRole('button', { name: 'Create', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Create Dock' })).toBeVisible();
});

test('Ensure cannot create duplicate dock code', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('link', { name: 'Docks' }).click();
  await page.getByRole('link', { name: 'add Create Dock' }).click();
  await page.getByPlaceholder('Dock code').click();
  await page.getByPlaceholder('Dock code').fill('DCKDUP01');
  await page.getByPlaceholder('Dock name').click();
  await page.getByPlaceholder('Dock name').fill('Duplicate Dock Test');
  await page.getByPlaceholder('Dock location').click();
  await page.getByPlaceholder('Dock location').fill('West Terminal');
  await page.getByPlaceholder('Length in meters').click();
  await page.getByPlaceholder('Length in meters').fill('500');
  await page.getByPlaceholder('Depth in meters').click();
  await page.getByPlaceholder('Depth in meters').fill('33');
  await page.getByPlaceholder('Draft in meters').click();
  await page.getByPlaceholder('Draft in meters').fill('29');
  await page.getByPlaceholder('Select supported vessel types').click();
  await page.locator('.option').first().click();
  await page.getByRole('button', { name: 'Create', exact: true }).click();
  await page.getByRole('link', { name: 'add Create Dock' }).click();
  await page.getByPlaceholder('Dock code').click();
  await page.getByPlaceholder('Dock code').fill('DCKDUP01');
  await page.getByPlaceholder('Dock name').click();
  await page.getByPlaceholder('Dock name').fill('Another dock with same code');
  await page.getByPlaceholder('Dock location').click();
  await page.getByPlaceholder('Dock location').fill('South Terminal');
  await page.getByPlaceholder('Length in meters').click();
  await page.getByPlaceholder('Length in meters').fill('680');
  await page.getByPlaceholder('Depth in meters').click();
  await page.getByPlaceholder('Depth in meters').fill('31');
  await page.getByPlaceholder('Draft in meters').click();
  await page.getByPlaceholder('Draft in meters').fill('28');
  await page.getByPlaceholder('Select supported vessel types').click();
  await page.locator('.option').first().click();
  await page.getByRole('button', { name: 'Create', exact: true }).click();
  await expect(page.getByText('An error has occured')).toBeVisible();
});
