import { test, expect } from '@playwright/test';

test('Ensure can create STS crane and listing works', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('link', { name: 'Physical Resources' }).click();
  await page.getByRole('link', { name: 'add Create Physical Resource' }).click();
  await page.locator('#pr-code').getByLabel('', { exact: true }).click();
  await page.locator('#pr-code').getByLabel('', { exact: true }).fill('STSPRADD');
  await page.locator('#pr-description').getByLabel('', { exact: true }).click();
  await page.locator('#pr-description').getByLabel('', { exact: true }).fill('test add sts crane');
  await page.locator('#pr-status').getByPlaceholder('Select an option').click();
  await page.locator('.option').first().click();
  await page.locator('#pr-setupTime #input').click();
  await page.locator('#pr-setupTime #input').press('ArrowLeft');
  await page.locator('#pr-setupTime #input').fill('10');
  await page.locator('#pr-servingDock-sts').click();
  await page.locator('sl-select#pr-servingDock-sts sl-option').first().click();
  await page.locator('#pr-liftingCapacity-sts').getByRole('textbox').click();
  await page.locator('#pr-liftingCapacity-sts').getByRole('textbox').fill('10');
  await page.locator('#pr-containersPerHour-sts').getByRole('textbox').click();
  await page.locator('#pr-containersPerHour-sts').getByRole('textbox').fill('5');
  await page.getByRole('button', { name: 'Create', exact: true }).click();
  await page.getByRole('link', { name: 'search View Physical' }).click();
  await page.getByRole('main').filter({ hasText: 'Physical Resource Dashboard' }).getByPlaceholder('Search...').click();
  await page.getByRole('main').filter({ hasText: 'Physical Resource Dashboard' }).getByPlaceholder('Search...').fill('test add sts crane');
  await expect(page.getByRole('link', { name: 'test add sts crane Available' })).toBeVisible();
});

test('Ensure can create yard crane and listing works', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('link', { name: 'Physical Resources' }).click();
  await page.getByRole('link', { name: 'add Create Physical Resource' }).click();
  await page.locator('#sl-tab-2 > .tab').click();
  await page.locator('#pr-code').getByLabel('', { exact: true }).click();
  await page.locator('#pr-code').getByLabel('', { exact: true }).fill('YGCADD');
  await page.locator('#pr-description').getByLabel('', { exact: true }).click();
  await page.locator('#pr-description').getByLabel('', { exact: true }).press('CapsLock');
  await page.locator('#pr-description').getByLabel('', { exact: true }).fill('test add yard crane');
  await page.locator('#pr-status').getByPlaceholder('Select an option').click();
  await page.locator('.option').first().click();
  await page.locator('#pr-setupTime #input').click();
  await page.locator('#pr-setupTime #input').fill('10');
  await page.locator('#pr-liftingCapacity-yard').getByRole('textbox').click();
  await page.locator('#pr-liftingCapacity-yard').getByRole('textbox').fill('10');
  await page.locator('#pr-containersPerHour-yard').getByRole('textbox').click();
  await page.locator('#pr-containersPerHour-yard').getByRole('textbox').fill('5');
  await page.getByRole('button', { name: 'Create', exact: true }).click();
  await page.getByRole('link', { name: 'search View Physical' }).click();
  await page.getByRole('main').filter({ hasText: 'Physical Resource Dashboard' }).getByPlaceholder('Search...').click();
  await page.getByRole('main').filter({ hasText: 'Physical Resource Dashboard' }).getByPlaceholder('Search...').fill('test add yard crane');
  await expect(page.getByRole('link', { name: 'test add yard crane Available' })).toBeVisible();
});

test('Ensure can create truck and listing works', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('link', { name: 'Physical Resources' }).click();
  await page.getByRole('link', { name: 'add Create Physical Resource' }).click();
  await page.locator('#sl-tab-3 > .tab').click();
  await page.locator('#pr-code').getByLabel('', { exact: true }).click();
  await page.locator('#pr-code').getByLabel('', { exact: true }).fill('TRCKADD');
  await page.locator('#pr-description').getByLabel('', { exact: true }).click();
  await page.locator('#pr-description').getByLabel('', { exact: true }).fill('test add truck');
  await page.locator('#pr-status').getByPlaceholder('Select an option').click();
  await page.locator('.option').first().click();
  await page.locator('#pr-setupTime #input').click();
  await page.locator('#pr-setupTime #input').fill('10');
  await page.locator('#pr-maxLoadCapacity-truck').getByRole('textbox').click();
  await page.locator('#pr-maxLoadCapacity-truck').getByRole('textbox').fill('10');
  await page.locator('#pr-averageSpeed-truck').getByRole('textbox').click();
  await page.locator('#pr-averageSpeed-truck').getByRole('textbox').fill('10');
  await page.locator('#pr-containersPerTrip-truck > .form-control > .form-control-input > .input > #input').click();
  await page.locator('.input.input--medium.input--filled.input--empty.input--focused > #input').fill('5');
  await page.getByRole('button', { name: 'Create', exact: true }).click();
  await page.getByRole('link', { name: 'search View Physical' }).click();
  await page.getByRole('main').getByPlaceholder('Search...').click();
  await page.getByRole('main').filter({ hasText: 'Physical Resource Dashboard' }).getByPlaceholder('Search...').fill('test add truck');
  await expect(page.getByRole('link', { name: 'test add truck Available' })).toBeVisible();
});

test('Ensure cant create physical resource with empty fields or invalid data', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('link', { name: 'Physical Resources' }).click();
  await page.getByRole('link', { name: 'add Create Physical Resource' }).click();
  await page.getByRole('button', { name: 'Create', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Create Physical Resource' })).toBeVisible();
});

test('Ensure cannot create duplicate physical resource', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('link', { name: 'Physical Resources' }).click();
  await page.getByRole('link', { name: 'search View Physical' }).click();
  await page.getByRole('main').filter({ hasText: 'Physical Resource Dashboard' }).getByPlaceholder('Search...').click();
  await page.getByRole('main').filter({ hasText: 'Physical Resource Dashboard' }).getByPlaceholder('Search...').fill('Truck 2');
  await expect(page.getByRole('link', { name: 'Truck 2 Maintenance TRK002' })).toBeVisible();
  await page.getByRole('link', { name: 'Physical Resources' }).click();
  await page.getByRole('link', { name: 'add Create Physical Resource' }).click();
  await page.locator('#sl-tab-3 > .tab').click();
  await page.locator('#pr-code').getByLabel('', { exact: true }).click();
  await page.locator('#pr-code').getByLabel('', { exact: true }).fill('TRK002');
  await page.locator('#pr-description').getByLabel('', { exact: true }).click();
  await page.locator('#pr-description').getByLabel('', { exact: true }).fill('Truck 2');
  await page.locator('#pr-status').getByPlaceholder('Select an option').click();
  await page.locator('.option').first().click();
  await page.locator('#pr-setupTime #input').click();
  await page.locator('#pr-setupTime #input').fill('10');
  await page.locator('#pr-maxLoadCapacity-truck').getByRole('textbox').click();
  await page.locator('#pr-maxLoadCapacity-truck').getByRole('textbox').fill('10');
  await page.locator('#pr-averageSpeed-truck').getByRole('textbox').click();
  await page.locator('#pr-averageSpeed-truck').getByRole('textbox').fill('10');
  await page.locator('#pr-containersPerTrip-truck > .form-control > .form-control-input > .input > #input').click();
  await page.locator('.input.input--medium.input--filled.input--empty.input--focused > #input').fill('10');
  await page.getByRole('button', { name: 'Create', exact: true }).click();
  await expect(page.locator('.alert__message')).toBeVisible();
});

test('Ensure can edit physical resource', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('link', { name: 'Physical Resources' }).click();
  await page.getByRole('link', { name: 'search View Physical' }).click();
  await page.getByRole('main').filter({ hasText: 'Physical Resource Dashboard' }).getByPlaceholder('Search...').click();
  await page.getByRole('main').filter({ hasText: 'Physical Resource Dashboard' }).getByPlaceholder('Search...').fill('Truck 2');
  await page.getByRole('link', { name: 'Truck 2 Maintenance TRK002' }).click();
  await page.getByRole('button', { name: 'Edit Physical Resource' }).click();
  await page.getByPlaceholder('Resource description').click();
  await page.getByPlaceholder('Resource description').fill('Truck 2 Edited');
  await page.getByRole('button', { name: 'Create' }).click();
  await expect(page.getByRole('heading')).toContainText('Truck 2 Edited');
  await page.getByRole('button', { name: 'Edit Physical Resource' }).click();
  await page.getByPlaceholder('Resource description').click();
  await page.getByPlaceholder('Resource description').fill('Truck 2');
  await page.getByRole('button', { name: 'Create' }).click();
  await expect(page.getByRole('heading')).toContainText('Truck 2');
});

test('Ensure can delete physical resource', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('link', { name: 'Physical Resources' }).click();
  await page.getByRole('link', { name: 'add Create Physical Resource' }).click();
  await page.locator('#sl-tab-3 > .tab').click();
  await page.locator('#pr-code').getByLabel('', { exact: true }).click();
  await page.locator('#pr-code').getByLabel('', { exact: true }).fill('TRKDELETE');
  await page.locator('#pr-description').getByLabel('', { exact: true }).click();
  await page.locator('#pr-description').getByLabel('', { exact: true }).fill('delete this physres');
  await page.locator('#pr-status').getByPlaceholder('Select an option').click();
  await page.locator('.option').first().click();
  await page.locator('#pr-setupTime #input').click();
  await page.locator('#pr-setupTime #input').fill('10');
  await page.locator('#pr-maxLoadCapacity-truck').getByRole('textbox').click();
  await page.locator('#pr-maxLoadCapacity-truck').getByRole('textbox').fill('10');
  await page.locator('#pr-averageSpeed-truck').getByRole('textbox').click();
  await page.locator('#pr-averageSpeed-truck').getByRole('textbox').fill('10');
  await page.locator('#pr-containersPerTrip-truck > .form-control > .form-control-input > .input > #input').click();
  await page.locator('.input.input--medium.input--filled.input--empty.input--focused > #input').fill('10');
  await page.getByRole('button', { name: 'Create', exact: true }).click();
  await page.getByRole('link', { name: 'search View Physical' }).click();
  await page.getByRole('main').filter({ hasText: 'Physical Resource Dashboard' }).getByPlaceholder('Search...').dblclick();
  await page.getByRole('main').filter({ hasText: 'Physical Resource Dashboard' }).getByPlaceholder('Search...').fill('delete this physres');
  await page.getByRole('link', { name: 'delete this physres Available' }).click();
  await page.getByRole('button', { name: 'Deactivate Physical Resource' }).click();
  await page.getByRole('button', { name: 'Deactivate', exact: true }).click();
  await page.getByRole('main').filter({ hasText: 'Physical Resource Dashboard' }).getByPlaceholder('Search...').click();
  await page.getByRole('main').filter({ hasText: 'Physical Resource Dashboard' }).getByPlaceholder('Search...').fill('delete this physres');
  await expect(page.getByRole('img', { name: 'No results.' })).toBeVisible();
});