import { test, expect } from '@playwright/test';

test('Ensure vessel type creation and search functionality', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('link', { name: 'Vessel Types' }).click();
  await page.getByRole('link', { name: 'add Create Vessel Type' }).click();
  await page.getByPlaceholder('Vessel type name').click();
  await page.getByPlaceholder('Vessel type name').fill('VTADD');
  await page.getByPlaceholder('Vessel type description').click();
  await page.getByPlaceholder('Vessel type description').fill('Add vessel type test');
  await page.getByPlaceholder('Length in meters').click();
  await page.getByPlaceholder('Length in meters').fill('100');
  await page.getByPlaceholder('Depth in meters').click();
  await page.getByPlaceholder('Depth in meters').fill('50');
  await page.getByPlaceholder('Draft in meters').click();
  await page.getByPlaceholder('Draft in meters').fill('50');
  await page.getByPlaceholder('Max Rows in TEU\'s').click();
  await page.getByPlaceholder('Max Rows in TEU\'s').fill('10');
  await page.getByPlaceholder('Max Bays in TEU\'s').click();
  await page.getByPlaceholder('Max Bays in TEU\'s').fill('10');
  await page.getByPlaceholder('Max Tiers in TEU\'s').click();
  await page.getByPlaceholder('Max Tiers in TEU\'s').fill('10');
  await page.getByRole('button', { name: 'Create', exact: true }).click();
  await page.getByRole('link', { name: 'search View Vessel Types' }).click();
  await page.getByRole('main').filter({ hasText: 'Vessel Type Dashboard Search' }).getByPlaceholder('Search...').click();
  await page.getByRole('main').filter({ hasText: 'Vessel Type Dashboard Search' }).getByPlaceholder('Search...').fill('VTADD');
  await expect(page.getByRole('link', { name: 'VTADD Add vessel type test' })).toBeVisible();
});

test('Ensure duplicate vessel type creation is handled', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('link', { name: 'Vessel Types' }).click();
  await page.getByRole('link', { name: 'add Create Vessel Type' }).click();
  await page.getByPlaceholder('Vessel type name').click();
  await page.getByPlaceholder('Vessel type name').fill('VTDUPLICATE');
  await page.getByPlaceholder('Vessel type description').click();
  await page.getByPlaceholder('Vessel type description').fill('Duplicate vesseltype test');
  await page.getByPlaceholder('Length in meters').click();
  await page.getByPlaceholder('Length in meters').fill('100');
  await page.getByPlaceholder('Depth in meters').click();
  await page.getByPlaceholder('Depth in meters').fill('50');
  await page.getByPlaceholder('Draft in meters').click();
  await page.getByPlaceholder('Draft in meters').fill('50');
  await page.getByPlaceholder('Max Rows in TEU\'s').click();
  await page.getByPlaceholder('Max Rows in TEU\'s').fill('10');
  await page.getByPlaceholder('Max Bays in TEU\'s').click();
  await page.getByPlaceholder('Max Bays in TEU\'s').fill('10');
  await page.getByPlaceholder('Max Tiers in TEU\'s').click();
  await page.getByPlaceholder('Max Tiers in TEU\'s').fill('10');
  await page.getByRole('button', { name: 'Create', exact: true }).click();
  await page.getByRole('link', { name: 'add Create Vessel Type' }).click();
  await page.getByPlaceholder('Vessel type name').click();
  await page.getByPlaceholder('Vessel type name').fill('VTDUPLICATE');
  await page.getByPlaceholder('Vessel type description').click();
  await page.getByPlaceholder('Vessel type description').fill('this vt already exists');
  await page.getByPlaceholder('Length in meters').click();
  await page.getByPlaceholder('Length in meters').fill('100');
  await page.getByPlaceholder('Depth in meters').click();
  await page.getByPlaceholder('Depth in meters').fill('50');
  await page.getByPlaceholder('Draft in meters').click();
  await page.getByPlaceholder('Draft in meters').fill('50');
  await page.getByPlaceholder('Max Rows in TEU\'s').click();
  await page.getByPlaceholder('Max Rows in TEU\'s').fill('10');
  await page.getByPlaceholder('Max Bays in TEU\'s').click();
  await page.getByPlaceholder('Max Bays in TEU\'s').fill('10');
  await page.getByPlaceholder('Max Tiers in TEU\'s').click();
  await page.getByPlaceholder('Max Tiers in TEU\'s').fill('10');
  await page.getByRole('button', { name: 'Create', exact: true }).click();
  await expect(page.locator('.alert.alert--closable.alert--has-countdown.alert--has-icon.alert--danger > .alert__message')).toBeVisible();
});

test('Ensure cannot create vessel type with empty fields or invalid data', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('link', { name: 'Vessel Types' }).click();
  await page.getByRole('link', { name: 'add Create Vessel Type' }).click();
  await page.getByRole('button', { name: 'Create', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Create Vessel Type' })).toBeVisible();
});

test('Ensure can edit vessel type', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('link', { name: 'Vessel Types' }).click();
  await page.getByRole('link', { name: 'add Create Vessel Type' }).click();
  await page.getByPlaceholder('Vessel type name').click();
  await page.getByPlaceholder('Vessel type name').fill('VTEDIT');
  await page.getByPlaceholder('Vessel type description').click();
  await page.getByPlaceholder('Vessel type description').fill('edit this vesseltype');
  await page.getByPlaceholder('Length in meters').click();
  await page.getByPlaceholder('Length in meters').fill('100');
  await page.getByPlaceholder('Depth in meters').click();
  await page.getByPlaceholder('Depth in meters').fill('50');
  await page.getByPlaceholder('Draft in meters').click();
  await page.getByPlaceholder('Draft in meters').fill('50');
  await page.getByPlaceholder('Max Rows in TEU\'s').click();
  await page.getByPlaceholder('Max Rows in TEU\'s').fill('10');
  await page.getByPlaceholder('Max Bays in TEU\'s').click();
  await page.getByPlaceholder('Max Bays in TEU\'s').fill('10');
  await page.getByPlaceholder('Max Tiers in TEU\'s').click();
  await page.getByPlaceholder('Max Tiers in TEU\'s').fill('10');
  await page.getByRole('button', { name: 'Create', exact: true }).click();
  await page.getByRole('link', { name: 'search View Vessel Types' }).click();
  await page.getByRole('main').filter({ hasText: 'Vessel Type Dashboard Search' }).getByPlaceholder('Search...').click();
  await page.getByRole('main').filter({ hasText: 'Vessel Type Dashboard Search' }).getByPlaceholder('Search...').fill('VTEDIT');
  await page.getByRole('link', { name: 'VTEDIT edit this vesseltype' }).click();
  await page.getByRole('button', { name: 'Edit Vessel Type' }).click();
  await page.getByPlaceholder('Vessel type description').click();
  await page.getByPlaceholder('Vessel type description').click();
  await page.getByPlaceholder('Vessel type description').fill('this vessel type was edited');
  await page.getByRole('button', { name: 'Save' }).click();
  await expect(page.getByRole('main')).toContainText('this vessel type was edited');
});