import { test, expect } from '@playwright/test';

test('Ensure vessel type is created with valid data and is listed', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('link', { name: 'Vessel Types' }).click();
  await page.getByRole('link', { name: 'add Create Vessel Type' }).click();
  await page.getByPlaceholder('Vessel type name').click();
  await page.getByPlaceholder('Vessel type name').fill('VESSELTYPETEST');
  await page.getByPlaceholder('Vessel type description').click();
  await page.getByPlaceholder('Vessel type description').fill('Test vessel type');
  await page.getByPlaceholder('Length in meters').click();
  await page.getByPlaceholder('Length in meters').fill('100');
  await page.getByPlaceholder('Depth in meters').click();
  await page.getByPlaceholder('Depth in meters').fill('20');
  await page.getByPlaceholder('Draft in meters').click();
  await page.getByPlaceholder('Draft in meters').fill('10');
  await page.getByPlaceholder('Max Rows in TEU\'s').click();
  await page.getByPlaceholder('Max Rows in TEU\'s').fill('10');
  await page.getByPlaceholder('Max Bays in TEU\'s').click();
  await page.getByPlaceholder('Max Bays in TEU\'s').fill('8');
  await page.getByPlaceholder('Max Tiers in TEU\'s').click();
  await page.getByPlaceholder('Max Tiers in TEU\'s').fill('6');
  await page.getByRole('button', { name: 'Create', exact: true }).click();
  await page.getByRole('link', { name: 'search View Vessel Types' }).click();
  await page.getByRole('main').filter({ hasText: 'Vessel Types Dashboard Search' }).getByPlaceholder('Search...').click();
  await page.getByRole('main').filter({ hasText: 'Vessel Types Dashboard Search' }).getByPlaceholder('Search...').fill('VESSELTYPETEST');
  await expect(page.getByRole('link', { name: 'VESSELTYPETEST' }).first()).toBeVisible();
});

test('Ensure vessel type is updated correctly on update', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('link', { name: 'Vessel Types' }).click();
  await page.getByRole('link', { name: 'add Create Vessel Type' }).click();
  await page.getByPlaceholder('Vessel type name').click();
  await page.getByPlaceholder('Vessel type name').fill('VESSELTYPEEDITTEST');
  await page.getByPlaceholder('Vessel type description').click();
  await page.getByPlaceholder('Vessel type description').fill('Edit test vessel type');
  await page.getByPlaceholder('Length in meters').click();
  await page.getByPlaceholder('Length in meters').fill('150');
  await page.getByPlaceholder('Depth in meters').click();
  await page.getByPlaceholder('Depth in meters').fill('25');
  await page.getByPlaceholder('Draft in meters').click();
  await page.getByPlaceholder('Draft in meters').fill('12');
  await page.getByPlaceholder('Max Rows in TEU\'s').click();
  await page.getByPlaceholder('Max Rows in TEU\'s').fill('12');
  await page.getByPlaceholder('Max Bays in TEU\'s').click();
  await page.getByPlaceholder('Max Bays in TEU\'s').fill('10');
  await page.getByPlaceholder('Max Tiers in TEU\'s').click();
  await page.getByPlaceholder('Max Tiers in TEU\'s').fill('7');
  await page.getByRole('button', { name: 'Create', exact: true }).click();
  await page.getByRole('link', { name: 'search View Vessel Types' }).click();
  await page.getByRole('main').filter({ hasText: 'Vessel Types Dashboard Search' }).getByPlaceholder('Search...').click();
  await page.getByRole('main').filter({ hasText: 'Vessel Types Dashboard Search' }).getByPlaceholder('Search...').fill('VESSELTYPEEDITTEST');
  await page.getByRole('link', { name: 'VESSELTYPEEDITTEST' }).first().click();
  await page.getByRole('button', { name: 'Edit Vessel Type' }).click();
  await page.getByPlaceholder('Length in meters').click();
  await page.getByPlaceholder('Length in meters').fill('200');
  await page.getByRole('button', { name: 'Save' }).click();
  await expect(page.getByText('200').first()).toBeVisible();
});

test('Ensure validation prevents creating vessel type with empty fields or incorrect data', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('link', { name: 'Vessel Types' }).click();
  await page.getByRole('link', { name: 'add Create Vessel Type' }).click();
  await page.getByRole('button', { name: 'Create', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Create Vessel Type' })).toBeVisible();
});

test('Ensure cannot create duplicate vessel type name', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('link', { name: 'Vessel Types' }).click();
  await page.getByRole('link', { name: 'add Create Vessel Type' }).click();
  await page.getByPlaceholder('Vessel type name').click();
  await page.getByPlaceholder('Vessel type name').fill('VESSELTYPEDUP');
  await page.getByPlaceholder('Vessel type description').click();
  await page.getByPlaceholder('Vessel type description').fill('Duplicate test');
  await page.getByPlaceholder('Length in meters').click();
  await page.getByPlaceholder('Length in meters').fill('80');
  await page.getByPlaceholder('Depth in meters').click();
  await page.getByPlaceholder('Depth in meters').fill('15');
  await page.getByPlaceholder('Draft in meters').click();
  await page.getByPlaceholder('Draft in meters').fill('8');
  await page.getByPlaceholder('Max Rows in TEU\'s').click();
  await page.getByPlaceholder('Max Rows in TEU\'s').fill('8');
  await page.getByPlaceholder('Max Bays in TEU\'s').click();
  await page.getByPlaceholder('Max Bays in TEU\'s').fill('6');
  await page.getByPlaceholder('Max Tiers in TEU\'s').click();
  await page.getByPlaceholder('Max Tiers in TEU\'s').fill('5');
  await page.getByRole('button', { name: 'Create', exact: true }).click();
  await page.getByRole('link', { name: 'add Create Vessel Type' }).click();
  await page.getByPlaceholder('Vessel type name').click();
  await page.getByPlaceholder('Vessel type name').fill('VESSELTYPEDUP');
  await page.getByPlaceholder('Vessel type description').click();
  await page.getByPlaceholder('Vessel type description').fill('Another vessel type with same name');
  await page.getByPlaceholder('Length in meters').click();
  await page.getByPlaceholder('Length in meters').fill('90');
  await page.getByPlaceholder('Depth in meters').click();
  await page.getByPlaceholder('Depth in meters').fill('18');
  await page.getByPlaceholder('Draft in meters').click();
  await page.getByPlaceholder('Draft in meters').fill('9');
  await page.getByPlaceholder('Max Rows in TEU\'s').click();
  await page.getByPlaceholder('Max Rows in TEU\'s').fill('9');
  await page.getByPlaceholder('Max Bays in TEU\'s').click();
  await page.getByPlaceholder('Max Bays in TEU\'s').fill('7');
  await page.getByPlaceholder('Max Tiers in TEU\'s').click();
  await page.getByPlaceholder('Max Tiers in TEU\'s').fill('6');
  await page.getByRole('button', { name: 'Create', exact: true }).click();
  await expect(page.getByText('An error has occured')).toBeVisible();
});
