@startuml auth_flow_v2
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor User as User
participant "U I" as FE <<presentation>>

participant "Cookie Store" as Cookie <<storage>>

participant "JwtBearerMiddleware" as JwtMiddleware <<middleware>>
participant "API" as ProtectedAPI <<application>>

title Authorization flow

FE -> ProtectedAPI: Request
activate ProtectedAPI

    ProtectedAPI -> JwtMiddleware: extract token
    activate JwtMiddleware
        alt no Authorization header
            JwtMiddleware -> Cookie: Try get AuthToken cookie
            Cookie --> JwtMiddleware: <JWT> (if present)
        end

        JwtMiddleware -> JwtMiddleware: Validate signature & claims
        note right: Uses TokenValidationParameters\n(Issuer, Audience(s), SigningKey, ClockSkew, RoleClaimType)
        JwtMiddleware --> ProtectedAPI: HttpContext.User
    deactivate JwtMiddleware

    ProtectedAPI -> ProtectedAPI: Policy check
    alt unauthorized
        ProtectedAPI --> FE: 401/403
    else authorized
        ProtectedAPI --> ProtectedAPI: Process request
        ProtectedAPI --> FE: Response
    end
deactivate ProtectedAPI

@enduml