@startuml sequence_diagram_post
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor User as Actor
participant "U I" as UI <<presentation>>
participant BackEnd as BackEnd <<C4 Component>>
database Database

title Register Xpto

Actor --> UI: Register new Xpto (data)
activate UI

    UI --> BackEnd: HTTP POST /api/xpto

    activate BackEnd

        BackEnd --> Database: SELECT
        activate Database
            Database --> BackEnd : xptoInstance?
        deactivate Database

        group if xpto not null
        BackEnd --> UI : HTTP Response
        UI --> Actor : Xpto already exists
        end

        BackEnd --> Database : INSERT Xpto(data)
        activate Database
            Database --> BackEnd : createdXpto
        deactivate Database

        BackEnd --> UI: HTTP Response
    deactivate BackEnd
UI --> Actor: Display created xpto
deactivate UI
            
@enduml