@startuml US2213_Domain_Model
title US2213 - Domain Model
hide circle

rectangle "System"{
	class "**User**" as user <<AggregateRoot>><<Entity>>
	{
		...
	}
}

rectangle "Physical Resources" {

	class "**Physical**\n**Resource**" as phys_res <<AggregateRoot>><<Entity>>
	{
		...
	}
}

rectangle "Staff"{

	class "**Staff**" as staff <<AggregateRoot>><<Entity>>
	{
		...
	}
}

rectangle "Qualifications" {
	class "**Qualification**" as quali <<AggregateRoot>><<Entity>>
	{
	}

	class "Qualification\n**Id**" as quali_id <<Identifier>>{
		+ id
	}

	class "Qualification\n**Name**" as quali_name <<Value>>{
		+ name
	}

	quali -u-> quali_id
	quali -u-> quali_name
}


user "1" ---> "*" quali : "(Logistics Operator)\nregisters/manages"

staff -u-> "*..*" quali : "has"

phys_res -u-> "*..*" quali : "requires"

@enduml