@startuml sequence_diagram_post
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor User as Actor
participant "U I" as UI <<presentation>>
participant API as API <<application>>
participant VesselVisitNotificationsController as Controller <<controller>>
participant NotificationDecisionService as Service <<service>>
participant NotificationDecisionFactory as Factory <<factory>>
participant VesselVisitNotificationsRepository as Repository <<repository>>
participant VesselVisitNotificationsContext as Context <<context>>
participant VesselVisitNotificationsModel as VVNModel <<entity>>
participant NotificationDecisionModel as Model <<entity>>
database Database

title Register Notification Decision

Actor --> UI: Register new Notification Decision
activate UI

    UI --> API: HTTP POST /api/VesselVisitNotifications/decisions

    activate API

        API --> Controller: route
        activate Controller

            Controller --> Service: Request registering
            activate Service

                Service --> Repository: GetVesselVisitNotificationByNotificationId(id)
                activate Repository
                    Repository --> Context: GetById(id)
                    activate Context
                    Context --> Database: SELECT
                    Context --> Repository: vesselVisitNotificationInstance?
                    deactivate Context
                    Repository --> Service: vesselVisitNotificationInstance?
                deactivate Repository

                group if vesselVisitNotificationInstance not exists
                    Service --> Controller: EntityNotFoundException
                    activate Controller
                        Controller --> API: NotFound()
                        activate API
                            API --> UI: HTTP Response
                        deactivate API
                        UI --> Actor: Error
                    deactivate Controller
                end

                Service --> Factory: CreateX(notificationDecisionDto) "CreateAccepted or CreateRejected"
                activate Factory
                    Factory --> Service: notificationDecision
                deactivate Factory

                Service --> Repository: Update(data)
                activate Repository
                
                    Repository --> VVNModel: Update(data)
                    Repository --> Context: Save(VesselVisitNotificationInstance)

                    activate Context
                        Context --> Database: UPDATE
                        Context --> Repository: status
                    deactivate Context

                    Repository --> Service: status
                deactivate Repository

                Service --> Model: toDto()
                activate Model
                    Model --> Service: notificationDecisionInstanceDto
                deactivate Model

                Service --> Controller: notificationDecisionInstanceDto
            deactivate Service

            Controller --> API: CreatedAt(notificationDecisionInstanceDto)
        deactivate Controller

        API --> UI: HTTP Reponse
    deactivate API
UI --> Actor: Results
deactivate UI
            
@enduml