@startuml domain model
rectangle "Physical Resources" {

	class "**Physical**\n**Resource**" as phys_res <<AggregateRoot>><<Entity>>
	{
	}

	class "Physical\nResources\n**STSCrane**" as sts_crane <<Entity>>
	{
	}

	class "Physical\nResources\n**YardCrane**" as yard_crane <<Entity>>
	{
	}

	class "Physical\nResources\n**Truck**" as truck <<Entity>>
	{
	}

	class "Physical\nResources\n**Active**" as phys_res_active <<Value>>
	{
		+ isActive
	}

	class "Physical\nResources\n**ContainersPerTrip**" as phys_res_cpt <<Value>>
	{
		+ containersPerTrip
	}

	class "Physical\nResources\n**AverageSpeed**" as phys_res_as <<Value>>
	{
		+ averageSpeed
	}

	class "Physical\nResources\n**ContainersPerHour**" as phys_res_cph <<Value>>
	{
		+ containersPerHour
	}

	class "Physical\nResources\n**LiftingCapacity**" as phys_res_lc <<Value>>
	{
		+ liftingCapacity
	}

	class "Physical\nResources\n**Description**" as phys_res_desc <<Value>>
	{
		+ description
	}

	class "Physical\nResources\n**Operational Capacity**" as phys_res_op_cap <<Value>>
	{
		+ operationalCapacity
	}

	class "Physical\nResources\n**Status**" as phys_res_status <<Value>>
	{
		+ status
	}

	class "Physical\nResources\n**Setup Time**" as phys_res_setup_time <<Value>>
	{
		+ setupTime
	}

	class "Physical\nResources\n**Operational Window**" as phys_res_op_window
	{
		+ startDay
		+ startTime
		+ endDay
		+ endTime
	}
}

rectangle "System"{
	class "**User**" as user <<AggregateRoot>><<Entity>>
	{
	}
}

rectangle "Dock" {
	class "**Dock**" as dock <<AggregateRoot>><<Entity>>
	{
	}
}

rectangle "Qualifications" {
	class "**Qualification**" as quali <<AggregateRoot>><<Entity>>
	{
	}
}


user "1" ---> "*" phys_res : "(Logistics Operator)\nregisters/manages"
phys_res "1" --> "1" phys_res_op_window : "has"
phys_res "*" --> "*" quali : "requires"
phys_res --> "1" phys_res_desc
phys_res --> "1" phys_res_op_cap
phys_res --> "1" phys_res_status
phys_res --> "1" phys_res_setup_time
phys_res --> "1" phys_res_active
dock "1" --> "*" phys_res : "has"
sts_crane --|> phys_res
yard_crane --|> phys_res
truck --|> phys_res
sts_crane --> "1" phys_res_cph
sts_crane --> "1" phys_res_lc
yard_crane --> "1" phys_res_cph
yard_crane --> "1" phys_res_lc
truck --> "1" phys_res_cpt
truck --> "1" phys_res_as

@enduml