@startuml mapping_view_n2
skinparam Linetype polyline

package "PortTiT" {
    package Backend  {

    }
}

circle "API" as api #LightBlue

api --o masterdata_implementation 


component "PorTiT" as masterdata_implementation <<system C4>> {
    
    [Master Data] as backend <<container C4>>
}

masterdata_implementation .l.> Backend : manifests

@enduml