@startuml
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor User as Actor
participant "U I" as UI <<presentation>>
participant API as API <<application>>
participant XptoController as Controller <<controller>>
participant XptoService as Service <<service>>
participant XptoRepository as Repository <<repository>>
participant XptoContext as Context <<context>>
participant XptoDto as Dto <<dto>>
participant XptoModel as Model <<entity>>
database Database

title Register Xpto

Actor --> UI: Register new Xpto
activate UI

    UI --> API: HTTP POST /api/xpto

    activate API

        API --> Controller: route
        activate Controller

            Controller --> Service: Request registering
            activate Service

                Service --> Repository: RegisterXpto(data)
                activate Repository
                
                    Repository --> Model: new()
                    activate Model
                        Model --> Model: validate()
                        Model --> Repository: XptoInstance
                    deactivate Model
                    Repository --> Context: Save(XptoInstance)

                    activate Context
                        Context --> Database: INSERT
                        Context --> Repository: status
                    deactivate Context

                    Repository --> Service: xptoInstance
                deactivate Repository

                Service --> Model: toDto()
                activate Model
                    Model --> Service: xptoInstanceDto
                deactivate Model

                Service --> Controller: xptoInstanceDto
            deactivate Service

            Controller --> API: Ok(xptoResponseDto)
        deactivate Controller

        API --> UI: HTTP Reponse
    deactivate API

deactivate UI
            
@enduml