import { inject, injectable } from 'inversify';
import { TYPES } from '@/inversify/types';

import type { Representative } from '@/model/Representative';
import type { IHttpService } from './IService/IHttpService';
import type { ISchedulingService } from './IService/ISchedulingService';
import type { Schedule } from '@/model/values/Schedule';
import jsPDF from 'jspdf';
import { useSession } from '@/composables/session';

@injectable()
export class SchedulingService implements ISchedulingService {

    constructor(
        @inject(TYPES.api)
        private http: IHttpService
    ) {}

    calculateDateOffset(baseDate: Date, offsetHours: number): Date {
        const newDate = new Date(baseDate.getTime() + offsetHours * 60 * 60 * 1000);
        return newDate;
    }    

    async generateSchedulePDF(schedule: Schedule, date: Date): Promise<Uint8Array> {
        
        const session = useSession();

        const doc = new jsPDF();

        doc.setFontSize(18);
        doc.text(`Schedule report`, 14, 22);

        doc.setFontSize(12);
        doc.text(`Concern: All docks, on day ${date.toDateString()}`, 14, 32);
        
        // Add metrics if available
        if (schedule.metrics) {
            doc.setFontSize(10);
            doc.text(`Algorithm: ${schedule.metrics.algorithm}`, 14, 40);
            doc.text(`Total Delay: ${schedule.metrics.totalDelay} hours`, 14, 46);
            doc.text(`Computation Time: ${(schedule.metrics.computationTime * 1000).toFixed(2)} ms`, 14, 52);
            doc.text(`Vessels Scheduled: ${schedule.metrics.vesselCount}`, 14, 58);
        }
        
        let yPosition = schedule.metrics ? 68 : 42;
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.text('Ship name', 14, yPosition);
        doc.text('Arrival', 64, yPosition);
        doc.text('Departure', 114, yPosition);
        doc.text('Cranes', 164, yPosition);

        doc.setFont('helvetica', 'normal');

        for (const entry of schedule.data) {
            console.log(entry);
            yPosition += 10;
            doc.text(entry.name, 14, yPosition);
            doc.text(this.calculateDateOffset(date, entry.loading_enter_time).toLocaleString(), 64, yPosition);
            doc.text(this.calculateDateOffset(date, entry.loading_exit_time).toLocaleString(), 114, yPosition);
            
            if ((entry as any).cranes) {
                const cranes = (entry as any).cranes;
                const craneText = Array.isArray(cranes) ? cranes.join(', ') : String(cranes);
                doc.text(craneText, 164, yPosition);
            } else {
                doc.text('-', 164, yPosition);
            }
        }

        doc.setFontSize(10);
        doc.text(`Generated by ${session.authenticatedUser?.name || 'Unknown user'} on ${new Date().toLocaleString()}`, 14, 290);

        const arrayBuffer = doc.output('arraybuffer') as ArrayBuffer;
        return new Uint8Array(arrayBuffer);
    }

    async scheduleForDay(day: Date, alg: string, daysAhead: number = 2): Promise<Schedule> {
        const dayString = day.toISOString().split('T')[0];
        const url = `/prolog/schedule?day=${dayString}&alg=${alg}&daysAhead=${daysAhead}`;
        const res = await this.http.getWithoutCredentials(url);
        
        const apiResponse = res as any;
        
        const actualData = apiResponse.data || {};
        
        return {
            status: actualData.status || 'success',
            comment: '',
            data: actualData.data || [],
            metrics: actualData.metrics
        } as Schedule;
    }
}