import { inject, injectable } from 'inversify';
import { TYPES } from '@/inversify/types';

import type { Representative } from '@/model/Representative';
import type { IHttpService } from './IService/IHttpService';
import type { ISchedulingService } from './IService/ISchedulingService';
import type { Schedule } from '@/model/Schedule';
import jsPDF from 'jspdf';
import { useSession } from '@/composables/session';

@injectable()
export class SchedulingService implements ISchedulingService {

    constructor(
        @inject(TYPES.api)
        private http: IHttpService
    ) {}

    calculateDateOffset(baseDate: Date, offsetHours: number): Date {
        const newDate = new Date(baseDate.getTime() + offsetHours * 60 * 60 * 1000);
        return newDate;
    }    

    async generateSchedulePDF(schedule: Schedule, date: Date, dock: string): Promise<Uint8Array> {
        
        const session = useSession();

        const doc = new jsPDF();

        doc.setFontSize(18);
        doc.text(`Schedule report`, 14, 22);

        doc.setFontSize(12);
        doc.text(`Concern: ${dock}, on day ${date.toDateString()}`, 14, 32);
        
        let yPosition = 42;
        doc.setFont('helvetica', 'bold');
        doc.text('Ship name', 14, yPosition);
        doc.text('Arrival', 64, yPosition);
        doc.text('Departure', 114, yPosition);

        doc.setFont('helvetica', 'normal');

        for (const entry of schedule.data) {
            console.log(entry);
            yPosition += 10;
            doc.text(entry.name, 14, yPosition);
            doc.text(this.calculateDateOffset(date, entry.loading_exit_time).toLocaleString(), 64, yPosition);
            doc.text(this.calculateDateOffset(date, entry.loading_enter_time).toLocaleString(), 114, yPosition);
        }

        doc.setFontSize(10);
        doc.text(`Generated by ${session.authenticatedUser?.name || 'Unknown user'} on ${new Date().toLocaleString()}`, 14, 290);

        return doc.output('arraybuffer') as Uint8Array;
    }

    async scheduleForDay(day: Date, dock: string, alg: string, daysAhead: number = 2): Promise<Schedule> {
        const dayString = day.toISOString().split('T')[0];
        const url = `http://localhost:8080/schedule?day=${dayString}&dock=${dock}&alg=${alg}&daysAhead=${daysAhead}`;
        const res = await this.http.getWithoutCredentials(url);
        return res.data as Schedule;
    }
}