import { Container } from "inversify";
import AxiosHttpService from "./service/AxiosHttpService";
import TYPES from "./inversify/types";
import { QualificationService } from "./service/QualificationService";
import { PhysicalResourceService } from "./service/PhysicalResourceService";
import { DockService } from "./service/DockService";
import { AdminService } from "./service/AdminService";
import { AuthService } from "./service/AuthService";
import { VesselService } from "./service/VesselService";
import { RepresentativeService } from "./service/RepresentativeService";
import { SchedulingService } from "./service/SchedulingService";
import { ShippingAgentOrganizationService } from "./service/ShippingAgentOrganizationService";
import { SystemNotificationService } from "./service/SystemNotificationService";
import { StaffService } from "./service/StaffService";
import { StorageAreaService } from "./service/StorageAreaService";
import { VesselTypeService } from "./service/VesselTypeService";
import { VesselVisitNotificationService } from "./service/VesselVisitNotificationService";
import { PrivacyPolicyService } from "./service/PrivacyPoliceService";
import { OperationPlanService } from "./service/OperationPlanService";
import { IncidentTypeService } from "./service/IncidentTypeService";
import { TaskCategoryService } from "./service/TaskCategoryService";
import { VesselVisitExecutionService } from "./service/VesselExecutionService";
import type { IQualificationService } from "./service/IService/IQualificationService";
import type { IHttpService } from "./service/IService/IHttpService";
import type { IPhysicalResourceService } from "./service/IService/IPhysicalResourceService";
import type { IAdminService } from "./service/IService/IAdminService";
import type { IDockService } from "./service/IService/IDockService";
import type { IAuthService } from "./service/IService/IAuthService";
import type { IRepresentativeService } from "./service/IService/IRepresentativeService";
import type { ISchedulingService } from "./service/IService/ISchedulingService";
import type { IShippingAgentOrganizationService } from "./service/IService/IShippingAgentOrganizationService";
import type { IStaffService } from "./service/IService/IStaffService";
import type { IStorageAreaService } from "./service/IService/IStorageAreaService";
import type { IVesselService } from "./service/IService/IVesselService";
import type { IVesselVisitNotificationService } from "./service/IService/IVesselVisitNotificationService";
import type { IVesselTypeService } from "./service/IService/IVesselTypeService";
import type { IPrivacyPolicyService } from "./service/IService/IPrivacyPolicyService";
import type { IOperationPlanService } from "./service/IService/IOperationPlanService";
import type { ISystemNotificationService } from "./service/IService/ISystemNotificationService";
import type { IIncidentTypeService } from "./service/IService/IIncidentTypeService";
import type { ITaskCategoryService } from "./service/IService/ITaskCategoryService";
import type { IVesselVisitExecutionService } from "./service/IService/IVesselExecutionService";
import type { IIncidentService } from "./service/IService/IIncidentService";
import { IncidentService } from "./service/IncidentService";

const container = new Container();

container.bind<IHttpService>(TYPES.api).to(AxiosHttpService).inSingletonScope();
container.bind<IAdminService>(TYPES.adminService).to(AdminService).inSingletonScope();
container.bind<IAuthService>(TYPES.authService).to(AuthService).inSingletonScope();
container.bind<IDockService>(TYPES.dockService).to(DockService).inSingletonScope();
container.bind<IPrivacyPolicyService>(TYPES.privacyPolicyService).to(PrivacyPolicyService).inSingletonScope();
container.bind<IPhysicalResourceService>(TYPES.physicalResourceService).to(PhysicalResourceService).inSingletonScope();
container.bind<IQualificationService>(TYPES.qualificationService).to(QualificationService).inSingletonScope();
container.bind<IRepresentativeService>(TYPES.representativeService).to(RepresentativeService).inSingletonScope();
container.bind<ISchedulingService>(TYPES.schedulingService).to(SchedulingService).inSingletonScope();
container.bind<IShippingAgentOrganizationService>(TYPES.shippingAgentOrganizationService).to(ShippingAgentOrganizationService).inSingletonScope();
container.bind<IStaffService>(TYPES.staffService).to(StaffService).inSingletonScope();
container.bind<IStorageAreaService>(TYPES.storageAreaService).to(StorageAreaService).inSingletonScope();
container.bind<IVesselService>(TYPES.vesselService).to(VesselService).inSingletonScope();
container.bind<IVesselTypeService>(TYPES.vesselTypeService).to(VesselTypeService).inSingletonScope();
container.bind<IOperationPlanService>(TYPES.operationPlanService).to(OperationPlanService).inSingletonScope();
container.bind<IVesselVisitNotificationService>(TYPES.vesselVisitNotificationService).to(VesselVisitNotificationService).inSingletonScope();
container.bind<ISystemNotificationService>(TYPES.systemNotificationService).to(SystemNotificationService).inSingletonScope();
container.bind<IIncidentTypeService>(TYPES.incidentTypeService).to(IncidentTypeService).inSingletonScope();
container.bind<ITaskCategoryService>(TYPES.taskCategoryService).to(TaskCategoryService).inSingletonScope();
container.bind<IVesselVisitExecutionService>(TYPES.vesselVisitExecutionService).to(VesselVisitExecutionService).inSingletonScope();
container.bind<IIncidentService>(TYPES.incidentService).to(IncidentService).inSingletonScope();

export { container };
