export const TYPES = {
    adminService: Symbol.for('AdminService'),
    authService: Symbol.for('AuthService'),
    dockService: Symbol.for('DockService'),
    privacyPolicyService: Symbol.for('PrivacyPolicyService'),
    physicalResourceService: Symbol.for('PhysicalResourceService'),
    operationPlanService: Symbol.for('OperationPlanService'),
    qualificationService: Symbol.for('QualificationService'),
    representativeService: Symbol.for('RepresentativeService'),
    schedulingService: Symbol.for('SchedulingService'),
    incidentTypeService: Symbol.for('IncidentTypeService'),
    shippingAgentOrganizationService: Symbol.for('ShippingAgentOrganizationService'),
    staffService: Symbol.for('StaffService'),
    storageAreaService: Symbol.for('StorageAreaService'),
    vesselService: Symbol.for('VesselService'),
    vesselTypeService: Symbol.for('VesselTypeService'),
    vesselVisitNotificationService: Symbol.for('VesselVisitNotificationService'),
    axiosInstance: Symbol.for('AxiosInstance'),
    systemNotificationService: Symbol.for('SystemNotificationService'),
    taskCategoryService: Symbol.for('TaskCategoryService'),
    vesselVisitExecutionService: Symbol.for('VesselVisitExecutionService'),
    api: Symbol.for('Api'),
};

export default TYPES;