@startuml us2211_domain_model
title US2211 - Class Diagram
skinparam backgroundColor #F0F0F0



class Staff
{
	- name : Designation
	- email : Email
	- phoneNumber : PhoneNumber
	- status : StaffStatus
	- operationalWindow : OperationalWindow
	- qualifications : List<Qualification>
	+ Staff(...) : void
	+ assignQualification(quali: Qualification)
	+ removeQualification(quali: Qualification)
}

class "Staff\n**Name**" as staff_name <<Value>>
{
	+ name
}
class "Staff\n**Email**" as staff_email <<Value>>
{
	+ email
}
class "Staff\n**Phone Number**" as staff_phone_number <<Value>>
{
	+ phoneNumber
}

class "Staff\n**Status**" as staff_status <<Enum>>
{
	+ ACTIVE
	+ INACTIVE
}

class "Staff\n**Operational**\n**Window**" as staff_op_window
{
	+ startDay
	+ startTime
	+ endDay
	+ endTime
}





@enduml