@startuml implementationview_n4
skinparam Linetype polyline

package "PortTiT" {

    package "Routes" as rt {

    }

    package "Application" {
        package "Controllers" as controller {

        }

        package "Services" as service{

        }
    }

    package "Infrastructure"{

        package "Persistency" {

            package "Repositories" as repo {

            }

            package "Context" as ctx {

            }
        }
    }

    package "Domain"{
        package "Entities" as ent {

        }

        package "ValueObjects" as vo {

        }
    }
}

controller ..> service
service ..> repo
service ..> ent

ent ..> vo

repo ..> ctx
rt ..> controller

@enduml