@startuml
title Business Domain Model

entity "System User" as user

entity "Port Authorities" as PA
entity "Shipping Agent\nOrganization (SAO)" as SAO
entity "SAO Representative" as SAOR
entity "Logistics Operators" as LO
entity "Administrator" as AD

class "Staff" as staff

class "Resource" as res

class "Docks" as docks
class "Ship-To-Shore cranes" as cranes
class "Yard gantry cranes" as yg_cranes
class "Trucks and terminal tractors" as trucks
class "Container yards" as yards
class "Warehouses" as warehouse

class "Vessels" as vessels
class "Vessel visit" as vessel_visit
class "Vessel cargo" as vessel_cargo
class "Cargo manifest" as cm

class "Tasks" as tasks

user --|> PA
user --|> SAOR
user --|> LO
user --|> AD

AD --> user : "manages"

PA --> SAO : "registers"
PA --> SAOR : "registers"
PA --> vessel_visit : "accepts or rejects"
PA --> warehouse : "regulates"
PA --> docks : "ensure proper allocation"
PA --> yards : "monitors capacity"

SAO --> SAOR : "has"

SAOR --> vessels : "represent"
SAOR --> vessel_visit : "submits"
SAOR --> cm : "submits"
SAOR --> vessel_cargo : "provides as information"


vessels --> vessel_cargo : "has"
vessel_visit --> vessels : "notify the berthing of"
cranes --> vessel_cargo : "unload or load"
docks --> vessels : "accomodate"
trucks --> vessel_cargo : "move"
yg_cranes --> vessel_cargo : "move"
warehouse --> vessel_cargo : "store for inspection"
yards --> vessel_cargo : "store temporarily"

res --|> cranes
res --|> yg_cranes
res --|> trucks

staff --> cranes : "operates"
staff --> yg_cranes : "operates"
staff --> trucks : "drives"

LO --> tasks : "schedules"
LO ---> staff : "manages"
LO --> docks : "manages"
LO --> cranes : "manages"
LO --> yg_cranes : "manages"
LO --> trucks : "manages"

cm --> tasks : "inform"
tasks --> res : "allocates"

@enduml

