@startuml domain_model
title Domain Model (DDD)
hide circle

rectangle "System"{
	class "**User**" as user <<AggregateRoot>><<Entity>>
	{
		+ userID
		+ name
		+ email
		+ password
		+ role
	}
	class "User Role" as urole
	{
		+ PORT_AUTHORITY_OFFICER
		+ SHIPPING_AGENT_REPRESENTATIVE
		+ LOGISTICS_OPERATOR
		+ ADMINISTRATOR
	}
}

rectangle "Vessel" {
	class "**Vessel**" as vessel <<AggregateRoot>><<Entity>>
	{
		+ IMO Number
		+ vesselName
		+ vesselType
		+ owner
	}

	class "Vessel Type" as vessel_type <<Value>>
	{
		+ Name
		+ Description
		+ maxNumberOfRows
		+ maxNumberOfBays
		+ maxNumberOfTiers
	}

}

rectangle "Resources and personnel" {

	class "**Physical**\n**Resource**" as phys_res <<Entity>>
	{
		+ resourceID
		+ description
		+ operationalCapacity
		+ status
		+ setupTime
		+ operationalWindow
	}

	class "Physical\nResources\nType" as phys_res_type
	{
		+ typeName
	}

	class "Qualification" as quali
	{
		+ qualificationID
		+ name
	}

	class "**Staff**" as staff <<Entity>>
	{
		+ staffID
		+ name
		+ email
		+ phoneNumber
		+ operationalWindow
		+ status
	}

	class "Operational Window" as op_window
	{
		+ startDay
		+ startTime
		+ endDay
		+ endTime
	}
}

rectangle "Dock" {
	class "**Dock**" as dock <<Entity>>
	{
		+ DockID
		+ DockName / DockNumber
		+ lenght
		+ depth
		+ maxDraft
	}

	dock "1" --> "*" phys_res : "has"
}

class "**Port**\n**Location**" as port_loc <<Entity>>
{
	- Location details \nmight include:
	+ General Location Name
	+ Latitude and Longitude
	+ Cardinal Direction
	+ etc...
}

rectangle "Storage Area"{

	class "**Storage**\n**Area**" as storage_area <<AggregateRoot>><<Entity>>
	{
		+ storageAreaID
		+ maxCapacity
		+ currentOccupancy
		+ complementaryInformation
	}

	class "Storage Area\nType" as storage_area_type <<Value>>{
		+ typeName
	}
}

class "**Shipping Agent**\n**Organization**" as SAO <<Entity>>
{
	+ SAOID
	+ legalName
	+ altNames
	+ address
	+ taxNumber
}

class "**SAO Representative**" as SAO_rep <<Entity>>
{
	+ name
	+ citizenID
	+ nationality
	+ email
	+ phoneNumber
}

rectangle "Berthing information" {

	class "**Vessel Visit**\n**Notification**" as vessel_visit_notif <<Entity>>
	{
		+ ETA
		+ ETD
		+ specialRequirements [?]
		+ captain [?]
		+ totalCrewMembers [?]
		+ isCargoHazardous
		+ loadManifest [?]
		+ unloadManifest [?]
	}

	class "Vessel Berth" as vessel_berth
	{
		+ dock
		+ taskSchedule
		+ status
	}

	enum "Cargo Type" as cargo_type
	{
		REEFERS
		GCP
		ELECTRONICS
		HAZMAT
		OIM
		OTHER
	}

	class "Notification\nDecision" as notif_dec
	{
		+ type
		+ timestamp
		+ reason
		+ outcome
		+ officerID
	}

	class "Cargo Manifest" as c_manifest {
		+ ISO
		+ description
		+ type
		+ bay
		+ row
		+ tier
	}


	class "Operational Task" as op_task
	{
		+ taskType
		+ resourceAllocated
		+ staffAllocated
		+ observations [?]
	}

	enum "Task Types" as task_types
	{
		LOADING
		UNLOADING
		MOVING
		OTHER
	}

	enum "Operation Status" as op_status
	{
		SCHEDULED
		FINISHED
		FAILED
		CANCELLED
	}


	class "Crewman" as crewman <<Value>>
	{
		+ citizenID
		+ name
		+ nationality
	}

}

user "1" -l-> "1" urole : "has"
user "1" --> "*" user : "(Admin)\nmanages"
user "1" ---> "*" dock : "(Port Authority Officer)\nregisters/manages"
user "1" ---> "*" storage_area : "(Port Authority Officer)\nregisters/manages"
user "1" ---> "*" vessel_type : "(Port Authority Officer)\nregisters/manages"
user "1" ---> "*" vessel_visit_notif : "(Port Authority Officer)\nreviews and approves or rejects"
user "1" ---> "*" op_task : "oversees"
user "1" ---> "*" SAO : "(Port Authority Officer)\nregisters"
user "1" ---> "*" SAO_rep : "(Port Authority Officer)\nregisters/manages"
user "1" ---> "*" vessel : "(Port Authority Officer)\nregisters/manages"
user "1" --> "*" notif_dec : "(Port Authority Officer)\nsubmits"
user "1" --> "*" staff : "(Logistics Operator)\nregisters/manages"
user "1" --> "*" phys_res : "(Logistics Operator)\nregisters/manages"
user "1" --> "*" quali : "(Logistics Operator)\nregisters/manages"
user "1" --> "*" op_task : "(Logistics Operator)\ndefines/schedules"


phys_res "1" --> "1" op_window : "has"
vessel_berth "1" -> "1" op_status : "has"
op_task "1" -> "1" phys_res : "allocates"
op_task "1" -> "*" staff : "mobilizes"
op_task "1" -> "1" task_types : "has"

staff "1" --> "1" op_window : "has"

vessel_berth "1" --> "*" op_task : "encapsulates"
vessel_berth "1" --> "1" dock : "happens on"
phys_res --> phys_res_type : "has"
phys_res --> "*..*" quali : "requires"
staff --> "*..*" quali : "has"

vessel_visit_notif -> "0..*" notif_dec
vessel_visit_notif <-- vessel_berth : "responds to"
vessel_visit_notif --> vessel
vessel_visit_notif --> crewman : "can have a list of"

SAO_rep --> vessel_visit_notif : "submits"

c_manifest "1" -> "1" cargo_type : "has"

vessel --> vessel_type

storage_area --> storage_area_type
storage_area --> port_loc
storage_area "1" --> "*" dock : "serves"

vessel --> SAO : "owns"
dock --> port_loc
SAO --> SAO_rep

@enduml