@startuml sequence_diagram_post
skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor User as Actor
participant "U I" as UI <<presentation>>
participant API as API <<application>>
participant XptoController as Controller <<controller>>
participant XptoService as Service <<service>>
participant XptoRepository as Repository <<repository>>
participant XptoContext as Context <<context>>
participant XptoModel as Model <<entity>>
database Database

title Register Xpto

Actor --> UI: Register new Xpto
activate UI

    UI --> API: HTTP POST /api/xpto

    activate API

        API --> Controller: route
        activate Controller

            Controller --> Service: Request registering
            activate Service

                Service --> Repository: GetXtpo(id)
                activate Repository
                    Repository --> Context: GetById(id)
                    activate Context
                    Context --> Database: SELECT
                    Context --> Repository: xptoInstance?
                    deactivate Context
                    Repository --> Service: xptoInstance?
                deactivate Repository

                group if xptoInstance exists
                    Service --> Controller: EntityAlreadyExistsException 
                    activate Controller
                        Controller --> API: Conflict()
                        activate API
                            API --> UI: HTTP Response
                        deactivate API
                        UI --> Actor: Error
                    deactivate Controller
                end

                Service --> Repository: RegisterXpto(data)
                activate Repository
                
                    Repository --> Model: new()
                    activate Model
                        Model --> Model: validate()
                        Model --> Repository: XptoInstance
                    deactivate Model
                    Repository --> Context: Save(XptoInstance)

                    activate Context
                        Context --> Database: INSERT
                        Context --> Repository: status
                    deactivate Context

                    Repository --> Service: xptoInstance
                deactivate Repository

                Service --> Model: toDto()
                activate Model
                    Model --> Service: xptoInstanceDto
                deactivate Model

                Service --> Controller: xptoInstanceDto
            deactivate Service

            Controller --> API: CreatedAt(xptoResponseDto)
        deactivate Controller

        API --> UI: HTTP Reponse
    deactivate API
UI --> Actor: Results
deactivate UI
            
@enduml