@startuml mapping_view_n3
skinparam Linetype polyline

title Level 3 - Logic Physical Mapping View

rectangle "Logic View"{
	circle " " as api

	rectangle "Master Data" as masterdata {
		
		[Backend] as backend

		database "Backend\nDatabase" as database

	} 

	api -- backend
	backend -(0- database : "Database\nApi"
}

rectangle "Physical View"{
	rectangle "localhost:??" as localhost {
		[Back end] as backend2
	}

	rectangle "vsgate-s1.dei.isep.ipp.pt:10383" as server1 {

		database Database 
	}

	backend2 -- Database : http/s
}

backend ...> backend2 : "<<manifests>>"
database ...> Database : "<<manifests>>"

@enduml
